name: OQuaRE Evaluation

on: workflow_dispatch

permissions:
 contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Evaluate ontologies
    steps:
      - uses: actions/checkout@v2
      # Configuration
      # Java setup
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      # Python setup
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: OQuaRE module
        uses: tecnomod-um/oquare-metrics@v2.2
        with:
          ontology-folders: gamificationOntologies
          contents-folder: OQUAREEVALGAM
